advocacia/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('core.urls')),
    url(r'^', include('sites.urls')),
    url(r'^', include('cliente.urls')),
    url(r'^', include('agenda.urls')),
    url(r'^', include('financeiro.urls')),
    url(r'^', include('blog.urls')),
    url(r'^', include('processos.urls')),
    url(r'^', include('controle_usuario.urls')),
    url(r'^', include('diario.urls')),
    url(r'^', include('processo_trabalhista.urls')),
]

blog/urls.py
from django.conf.urls import include, url
from django.views.generic import TemplateView
from blog.views import *
from . import views

urlpatterns = [
    url(r'^blog/$', views.post_list),
    url(r'^blog/all/posts/$', views.list),
    url(r'^blog/post/(?P<pk>[0-9]+)/$', views.post_detail),
    url(r'^blog/post/novo/$', views.post_new, name='post_new'),
    url(r'^blog/nova/tag/$', views.new_tag, name='new_tag'),
    url(r'^blog/post/(?P<pk>[0-9]+)/editar/$', views.post_edit, name='post_edit'),
    url(r'^blog/deletar/post(?P<pk>\d+)/$', views.excluir_post,name='excluir_post'),
    url(r'^tag/(?P<slug>[\w\-]+)/$', TagPostsView.as_view(), name='tag_posts_page'),
]

financeiro/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import include, url
from django.views.generic import TemplateView

from . import views

urlpatterns = [
    url(r'^contas/add_pagar/$', views.contaPagar),
    url(r'^contas/pagar/$', views.contas_pagar_lista),
    #url(r'^contas/$', views.contas),
    url(r'^contas/pagar/(?P<pk>\d+)/$', views.conta_detalhada_pagar),
    url(r'^contas/pagar/deletar/(?P<pk>\d+)/$', views.deletar_pagar),
    url(r'^contas/pagar/atualizar/(?P<pk>\d+)/$', views.atualizar_conta_pagar),
    url(r'^contas/pagar/aberta/$', views.conta_pagar_aberta),
    url(r'^contas/pagar/pagas/$', views.conta_apagar_pagas),
    url(r'^contas/pagar/fixas/$', views.contas_fixas),
    url(r'^add/categoria/$', views.add_categoria,name="categoria"),
    ###grafico
    url(r'^contas/pagar/receitas/$', views.receitas),

    url(r'^contas/add_receber/$', views.contaReceber),
    url(r'^contas/add_receber/(?P<pk>\d+)/$', views.contaReceber),
    url(r'^contas/receber/$', views.contas_receber_lista),
    url(r'^contas/receber/(?P<pk>\d+)/$', views.conta_detalhada_receber),
    url(r'^contas/receber/deletar/(?P<pk>\d+)/$', views.deletar_receber),
    url(r'^contas/receber/atualizar/(?P<pk>\d+)/$', views.atualizar_conta_receber),
    url(r'^contas/receber/aberta/$', views.conta_receber_aberta),
    url(r'^contas/receber/pagas/$', views.conta_receber_pagas),
    url(r'^contas/parcela/(?P<pk>\d+)/$', views.pagar_parcela),
]

financeiro/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.utils.translation import ugettext_lazy as _
from .choices import pagamentos
from .choices import parcelas
from processos.models import Processo


class Categoria(models.Model):

    desc = models.CharField(verbose_name='Descrição', max_length=200, null=True, blank=True)

    class Meta:
        verbose_name = _('Categoria')
        verbose_name_plural = _('Categorias')

    def __str__(self):
        return str(self.desc)

class Conta(models.Model):

    vencimento    = models.DateField(blank=False, null=True)
    valor_total   = models.CharField(null=False, blank=False,max_length=20)
    n_parcela     = models.IntegerField(default=1, choices=parcelas,blank=True,verbose_name="Nº Da Parcela")
    status_pag    = models.BooleanField(default=False)
    forma_pagamento = models.CharField(max_length=100, null=False, blank=False, choices=pagamentos)
    criado_em     = models.DateTimeField(auto_now_add=True)
    atualizado_em = models.DateTimeField(auto_now=True)
    valor_entrada = models.CharField(default = 0,null=False, blank=False,max_length=20)
    valor_parcela = models.CharField(default = 0,null=False, blank=False,max_length=20)
    categoria     = models.ForeignKey(Categoria, null=True, blank=True)

    class Meta:
        ordering = ('-vencimento',)
        verbose_name = _('Conta')
        verbose_name_plural = _('Contas')

    def __str__(self):
        return str(self.id)


class Conta_receber(Conta):

    descricao  = models.TextField(verbose_name='Descrição',max_length=200, null=True, blank=True)
    observacao = models.TextField(verbose_name='Observação', max_length=200, null=True, blank=True)
    processo = models.ForeignKey(Processo, null=True, blank=True)

    class Meta:
        verbose_name = _('Conta à receber')
        verbose_name_plural = _('Contas à receber')


class Conta_pagar(Conta):
    conta_fixa = models.NullBooleanField(default=False)
    descricao  = models.TextField(verbose_name='Descrição',max_length=200, null=True, blank=True)
    observacao = models.TextField(verbose_name='Observação',max_length=200, null=True, blank=True)

    class Meta:
        verbose_name = _('Conta à pagar')
        verbose_name_plural = _('Contas à pagar')


class Parcela(models.Model):

    conta      = models.ForeignKey(Conta)
    vencimento = models.DateField(blank=False, null=False)
    status_pag = models.BooleanField(default=False)
    data_pag   = models.DateField(blank=True, null=True)

    class Meta:
        verbose_name = _('Parcela')
        verbose_name_plural = _('Parcelas')

    def __str__(self):
        return str(self.id) + str(self.vencimento)

financeiro/forms.py
from django.forms import *
from .models import Conta_receber
from .models import Conta_pagar
from .models import Parcela
from .models import Categoria


class Conta_receberForm(ModelForm):

    class Meta:
        model = Conta_receber
        exclude = ['valor_parcela','categoria']
        widgets = {
                'descricao': TextInput(attrs={'class': 'form-control'}),
                'vencimento': DateInput(attrs={'class': 'form-control','placeholder':'dd/mm/aaaa','data-language': 'pt'}),
                'valor_total': TextInput(attrs={'class': 'form-control','placeholder':'R$ 0,00'}),
                'n_parcela': Select(attrs={'class':'form-control'}),
                'status_pag':CheckboxInput,
                'conta_fixa':NullBooleanSelect(attrs={'class':'form-control'}),
                'forma_pagamento':Select(attrs={'class':'form-control'}),
                'observacao':Textarea(attrs={'class':'form-control','rows':5}),
                'valor_entrada': TextInput(attrs={'class': 'form-control','placeholder':'R$ 0,00'}),
            }


class Conta_pagarForm(ModelForm):

    class Meta:
        model = Conta_pagar
        exclude = ['id_conta','valor_parcela']
        widgets = {
                'descricao': TextInput(attrs={'class': 'form-control'}),
                'vencimento': DateInput(attrs={'class': 'form-control','placeholder':'dd/mm/aaaa','data-language': 'pt'}),
                'valor_total': TextInput(attrs={'class': 'form-control','placeholder':'R$ 0,00'}),
                'n_parcela': Select(attrs={'class':'form-control'}),
                'status_pag':CheckboxInput,
                'conta_fixa':NullBooleanSelect(attrs={'class':'form-control'}),
                'forma_pagamento':Select(attrs={'class':'form-control'}),
                'observacao':Textarea(attrs={'class':'form-control','rows':5}),
                'valor_entrada': TextInput(attrs={'class': 'form-control','placeholder':'R$ 0,00'}),
                'categoria':Select(attrs={'class':'form-control'}),
            }


class CategoriaForm(ModelForm):

    class Meta:
        model = Categoria
        exclude = ['']

        widgets = {
            'desc': TextInput(attrs={'class': 'form-control','name':'desc'})
        }

class ParcelaForm(ModelForm):

    class Meta:
        model = Parcela
        exclude = ['']

financeiro/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render,get_object_or_404
from .models import Conta_pagar
from .models import Conta_receber
from .models import Parcela
from .models import Conta
from .forms import *
from processos.models import Processo
from django.shortcuts import redirect
from dateutil.relativedelta import relativedelta
from django.http import HttpResponse as response
from django.core import serializers
from django.http import JsonResponse
import json
from django.template.loader import render_to_string
from django.http import HttpResponse
from django.utils import timezone
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import permission_required
from django.contrib.auth.decorators import login_required
import datetime
import json
from django.template.loader import render_to_string
from django.core.exceptions import ObjectDoesNotExist


def converterValor(valor):
    valor = valor[3:]
    valor = valor.replace('.', '')
    valor = valor.replace(',', '.')
    return float(valor)
def converterV(valor):
    valor = valor[2:]
    valor = valor.replace('.', '')
    valor = valor.replace(',', '.')
    return float(valor)


@login_required(login_url='/usuario/login/')
@permission_required('global_permissions.financeiro', login_url='/usuario/error/')
def contaPagar(request):

    if request.method == "POST":
        form = Conta_pagarForm(request.POST)
        if form.is_valid():
            conta_pagar = form.save()
            # converter para númerico

            if (conta_pagar.forma_pagamento == 'Cartão de credito' or conta_pagar.forma_pagamento == 'Cheque'):
                v_total = converterValor(conta_pagar.valor_total)
                v_entrada = converterValor(conta_pagar.valor_entrada)
                v_total = v_total - v_entrada
                conta_pagar.valor_total = str('R$ ') + str(v_total) + str('0')
                conta_pagar.valor_parcela = v_total / conta_pagar.n_parcela
                conta_pagar.save()

                for i in range(conta_pagar.n_parcela):
                    parcela = Parcela()
                    parcela.conta_id = conta_pagar.id
                    parcela.vencimento = conta_pagar.vencimento
                    parcela.save()
                    conta_pagar.vencimento = conta_pagar.vencimento + relativedelta(months=1)
            else:
                conta_pagar.n_parcela = 0
                conta_pagar.valor_entrada = 0
                conta_pagar.valor_parcela = 0
                conta_pagar.save()

            return redirect("/contas/pagar/")
    else:
        form = Conta_pagarForm()
    return render(request, 'a_pagar/contas_pagar_add.html', {'form': form})


@login_required(login_url='/usuario/login/')
@permission_required('global_permissions.financeiro', login_url='/usuario/error/')
def contaReceber(request, pk = None):

    if request.method == "POST":
        form = Conta_receberForm(request.POST)
        if form.is_valid():
            conta_receber = form.save()
            # converter dados para numerico
            if pk != None:
                p = Processo.objects.get(pk=pk)
                conta_receber.processo = p

            if (conta_receber.forma_pagamento == 'Cartão de credito' or conta_receber.forma_pagamento == 'Cheque'):
                v_total = converterValor(conta_receber.valor_total)
                v_entrada = converterValor(conta_receber.valor_entrada)
                v_total = v_total - v_entrada
                conta_receber.valor_total = str('R$ ') + str(v_total) + str('0')
                conta_receber.valor_parcela = v_total / conta_receber.n_parcela
                conta_receber.save()

                for i in range(conta_receber.n_parcela):
                    parcela = Parcela()
                    parcela.conta_id = conta_receber.id
                    parcela.vencimento = conta_receber.vencimento
                    parcela.save()
                    conta_receber.vencimento = conta_receber.vencimento + relativedelta(months=1)
            else:
                conta_receber.n_parcela = 0
                conta_receber.valor_entrada = 0
                conta_receber.valor_parcela = 0
                conta_receber.save()

            return redirect("/contas/receber/")
    else:
        form = Conta_receberForm()
        if pk != None:
            try:
                c = Conta_receber.objects.get(processo_id = pk)
                return redirect("/contas/receber/"+str(c.id)+"/")
            except ObjectDoesNotExist:
                print('objeto nao existe')

            p = Processo.objects.get(pk=pk)            
            form.initial['descricao'] = p.cliente.nome +' || '+p.numero_processo
            form.initial['observacao'] = 'Cliente:' + p.cliente.nome +'\n' +'N° Processo:'+ p.numero_processo+'\n'
            form.initial['observacao'] += 'Data do processo:'+ p.data_abertura.strftime('%Y-%m-%d %H:%M') +'\n'+ 'Advogado:' +p.usuario.user.first_name+''+ p.usuario.user.last_name
        return render(request, 'a_receber/contas_receber_add.html', {'form': form})

"""
@login_required(login_url='/usuario/login/')
def contas(request):
    contas = Conta_pagar.objects.all()
    data = serializers.serialize('json', contas)
    return HttpResponse(data)

"""


@login_required(login_url='/usuario/login/')
@permission_required('global_permissions.financeiro', login_url='/usuario/error/')
def contas_pagar_lista(request):

    if request.is_ajax():
        a = Conta_pagar.objects.filter(id=0)
        b = Conta_pagar.objects.filter(id=0)

        contas = Conta_pagar.objects.all()
        if(request.GET.get('aberta') == 's'):
            a = contas.filter(status_pag=False)

        if(request.GET.get('paga') == 's'):
            a = contas.filter(status_pag=True)

        if(request.GET.get('fixas') == 's'):
            b = contas.filter(conta_fixa=True)

        conta = list(Conta.objects.filter(id__in=a | b))
        conta_p = list(a | b)
        z = dict()
        aux = []

        for i in range(0, len(conta)):
            aux.append([conta[i], conta_p[i]])

        for i in range(0, len(conta)):
            z.update({i: serializers.serialize('json', aux[i])})

        return HttpResponse(json.dumps(z, ensure_ascii=True), content_type='application/json')
    else:
        contas = Conta_pagar.objects.all()

    return render(request, 'a_pagar/contas_pagar.html', {'contas': contas})


@login_required(login_url='/usuario/login/')
@permission_required('global_permissions.financeiro', login_url='/usuario/error/')
def contas_receber_lista(request):

    if request.is_ajax():
        a = Conta_receber.objects.filter(id=0)
        b = Conta_receber.objects.filter(id=0)

        contas = Conta_receber.objects.all()
        if(request.GET.get('aberta') == 's'):
            a = contas.filter(status_pag=False)

        if(request.GET.get('paga') == 's'):
            a = contas.filter(status_pag=True)

        if(request.GET.get('fixas') == 's'):
            b = contas.filter(conta_fixa=True)

        conta = list(Conta.objects.filter(id__in=a | b))
        conta_p = list(a | b)
        z = dict()
        aux = []

        for i in range(0, len(conta)):
            aux.append([conta[i], conta_p[i]])

        for i in range(0, len(conta)):
            z.update({i: serializers.serialize('json', aux[i])})

        return HttpResponse(json.dumps(z, ensure_ascii=True), content_type='application/json')
    else:
        contas = Conta_receber.objects.all()

    return render(request, 'a_receber/contas_receber.html', {'contas': contas})


@login_required(login_url='/usuario/login/')
@permission_required('global_permissions.financeiro', login_url='/usuario/error/')
def conta_detalhada_pagar(request, pk):

    conta = Conta_pagar.objects.get(id=pk)
    parcela = Parcela.objects.filter(conta_id=conta.id)

    context = dict(
        conta=conta,
        parcela=parcela
    )

    return render(request, 'a_pagar/conta_detalhada_pagar.html', context)


@login_required(login_url='/usuario/login/')
@permission_required('global_permissions.financeiro', login_url='/usuario/error/')
def conta_detalhada_receber(request, pk):
    conta = Conta_receber.objects.get(id=pk)
    parcela = Parcela.objects.filter(pk=conta.pk)

    context = dict(
        conta=conta,
        parcela=parcela,
    )
    return render(request, 'a_receber/conta_detalhada_receber.html', context)


@login_required(login_url='/usuario/login/')
@permission_required('global_permissions.financeiro', login_url='/usuario/error/')
def deletar_pagar(request, pk):
    conta = get_object_or_404(Conta_pagar,pk=pk)
    data = dict()
    if request.method == 'POST':
        conta.delete()
        data['form_is_valid'] = True
        return redirect('/contas/pagar/')
    else:
        context = {'conta': conta}
        data['html_form'] = render_to_string('modal_delete.html', context, request=request)
    return JsonResponse(data)


@login_required(login_url='/usuario/login/')
@permission_required('global_permissions.financeiro', login_url='/usuario/error/')
def deletar_receber(request, pk):
    conta = get_object_or_404(Conta_receber,pk=pk)
    data = dict()
    if request.method == 'POST':
        conta.delete()
        data['form_is_valid'] = True
        return redirect('/contas/receber/')
    else:
        context = {'c': conta}
        data['html_form'] = render_to_string('a_receber/deletar.html', context, request=request)
    return JsonResponse(data)

@login_required(login_url='/usuario/login/')
@permission_required('global_permissions.financeiro', login_url='/usuario/error/')
def atualizar_conta_pagar(request, pk):
    conta = Conta_pagar.objects.get(id=pk)

    context = dict(
        form=Conta_pagarForm(instance=conta)
    )

    if request.POST:
        form = Conta_pagarForm(request.POST, instance=conta)

        if not form.is_valid():
            return render(
                request, 'a_pagar/contas_pagar_add.html', dict(

financeiro/templates/a_receber/conta_detalhada_receber.html
{% extends "base_sistema.html" %}
{% load staticfiles %}
{% block title %}
    Detalhes
{% endblock title %}
{% block conteudo %}
	<div class="col-md-1"></div>
	   <div class="col-lg-10">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    $ Detalhes da conta à receber
                </div>
                    <!-- /.panel-heading -->
                    <div class="panel-body">
                        <div class="list-group">
                            <li href="#" class="list-group-item">
                                <i class="fa fa-calendar-o fa-fw"></i> Vencimento:
                                <span class="pull-right text-muted small"><b>{{conta.vencimento }}
                                </span>
                             </li>
                              <li href="#" class="list-group-item">
                                <i class="fa fa-pencil-square-o fa-fw"></i><b>Descrição:</b> 
                                <span class="pull-right text-muted small"><b>{{conta.descricao }}
                                </span>
                            </li>
                            <li href="#" class="list-group-item">
                                &nbsp;$ Valor Total:
                                <span class="pull-right text-muted small"><b>{{conta.valor_total }}</b>
                                </span>
                            </li>
                             <li href="#" class="list-group-item">
                                    &nbsp;$ Valor Parcela:
                                <span class="pull-right text-muted small"><b>R$ {{conta.valor_parcela }}</b>
                                </span>
                            </li>
                            <li href="#" class="list-group-item">
                                <i class="fa fa-leaf fa-fw"></i>Numero de parcelas:
                                <span class="pull-right text-muted small"><b>{{conta.n_parcela }}</b>
                                </span>
                            </li>
                            <li href="#" class="list-group-item">
                                <i class="fa fa-credit-card fa-fw"></i> Formas de pagamento:
                                <span class="pull-right text-muted small"><b> {{conta.forma_pagamento }}</b>
                                </span>
                            </li>
                            <li href="#" class="list-group-item">
                                <i class="fa fa-check fa-fw"></i> Status de pagamento:
                                <span class="pull-right text-muted small">
                                    {% if conta.status_pag == True %}
                                        <i id="pago" class="fa fa-check text-success" aria-hidden="true"></i> 
                                    {% else %}
                                        <i id="aberto" class="fa fa-times text-danger" aria-hidden="true"></i>
                                    {% endif %}
                                </span>
                            </li>     
                        </div>
                        <div class="col-md-4">
                            <a href="/contas/receber/" class="btn btn-success btn-block"> <i class="fa fa-arrow-left fa-fw"></i> Voltar</a>
                        </div>
                        <div class="col-md-4">
                            <a class="btn btn-danger btn-block js-delete-conta-receber" id="{{conta.id}}"><i class="fa fa-trash-o fa-fw"></i> Deletar</a>
                        </div>
                         <div class="col-md-4">
                            <a href="/contas/receber/atualizar/{{conta.id}}/"class="btn btn-warning btn-block"><i class="fa fa-pencil-square-o fa-fw"></i> Editar</a>
                        </div>
                </div>
                    <!-- /.panel-body -->
            <!--deletar-->
                <div class="modal fade" id="delete-conta-modal" >
                    <div class="modal-dialog" role="document">
                        <div class="modal-content">
                            
                        </div>
                    </div>
                </div>
            </div>
        <div class="row">
            {% for Parcelas in conta.parcela_set.all %}
                 <div class="col-md-3">
                    <div class="panel panel-default ">
                      <div class="panel-heading">Parcela Nº {{forloop.counter}}</div>
                      <div class="panel-body text-center">
                            <i class="fa fa-calendar-o fa-fw"></i> Vencimento:<br> {{Parcelas.vencimento }}<br>
                            <i class="fa fa-check fa-fw"></i>
                             Status do Pagamento:<br>
                            {% if Parcelas.status_pag == True %}
                                <i class="fa fa-check text-success" aria-hidden="true"></i>
                                <i class="fa fa-calendar-o fa-fw"></i> Pago Em:<br> {{Parcelas.data_pag }}<br> 
                            {% else %}
                                <i class="fa fa-times text-danger" aria-hidden="true"></i><br>
                                <a href="/contas/parcela/{{Parcelas.id}}/">Pagar</a>
                            {% endif %}<br>
                      </div>
                    </div>
                </div> 
            {% endfor %} 
         </div>   
    </div>
{% endblock %}
{% block js %}{% endblock %}
{% block js_financeiro %}
    <script src="{% static "js/modal.js" %}"></script>
{% endblock js_financeiro %}

financeiro/templates/a_receber/contas_receber_add.html
{% extends "base_sistema.html" %}
{% load static %}
{% block title %}
   add Novo
{% endblock title %}
{% block financeiro %}
	<link href="{% static "css/admin/calendario.min.css" %}" rel="stylesheet" >
    <script src="{% static "js/datepicker.min.js" %}"></script>
    <script src="{% static "js/datepicker.pt.js" %}"></script>
{% endblock %}
{% block conteudo %}
	<div class="panel panel-primary">
		<div class="panel-heading">
			<h3 class="panel-title text-center">CADASTRAR CONTA À RECEBER</h3>
		</div>
		<div class="panel-body">
			<form action="" class="form-horizontal" method="POST">
				{% csrf_token %}
					<div class="form-group">
						<label for="criacao" class="col-sm-2 control-label">{{form.descricao.label}} <i class="fa fa-pencil-square-o" aria-hidden="true"></i></label>
						<div class="col-sm-4">
							{{ form.descricao }}
						</div>
					</div>
					<div class="form-group">
						<label for="titulo" class="col-sm-2 control-label">{{form.vencimento.label}}  <i class="fa fa-calendar" aria-hidden="true"></i></label>
						<div class="col-sm-4">
						{{form.vencimento.errors}}
							{{form.vencimento}}
						</div>
					</div>
					<div class="form-group">
						<label for="data" class="col-sm-2 control-label">{{form.valor_total.label}} $</label>
						<div class="col-sm-4">
							{{form.valor_total}}
						</div>
					</div>
					<div class="form-group">
						<label for="criacao" class="col-sm-2 control-label">{{form.forma_pagamento.label}} <i class="fa fa-credit-card" aria-hidden="true"></i></label>
						<div class="col-sm-4">
							{{ form.forma_pagamento }}
						</div>
					</div>
					<div id="n_parcela">
						<div class="form-group"id="n_parcela">
							<label for="data" class="col-sm-2 control-label">{{form.valor_entrada.label}} $</label>
							<div class="col-sm-4">
								{{form.valor_entrada}}
							</div>
						</div>
						<div class="form-group"id="n_parcela">
							<label class="col-sm-2 control-label">{{form.n_parcela.label}} <i class="fa fa-calculator" aria-hidden="true"></i></label>
							<div class="col-sm-4">
								{{form.n_parcela}}
							</div>
						</div>
					</div>
						<div id="id_conta_fixa"></div>
						<div class="form-group">
							<label for="id_status_pag" class="col-sm-2 control-label">{{form.status_pag.label}} <i class="fa fa-check" aria-hidden="true"></i> </label>
							<div class="col-sm-4">
								{{ form.status_pag}}
							</div>
						</div>
					<div class="form-group">
						<label for="criacao" class="col-sm-2 control-label">{{form.observacao.label}} <i class="fa fa-pencil" aria-hidden="true"></i></label>
						<div class="col-sm-4">
							{{ form.observacao }}
						</div>
					</div>
				<button type="submit" class="btn btn-primary">
					<span class="glyphicon glyphicon-floppy-disk" aria-hidden="true"></span> Salvar
				</button>
				<a class="btn btn-success" href="/contas/receber/"><i class="fa fa-arrow-left" aria-hidden="true"></i>  Voltar</a>
			</form>
		</div>
	</div>
	{% block contas_js %}
		<script src="{% static "js/contas.js" %}"></script>
	{% endblock contas_js %}
{% endblock %}

financeiro/templates/a_receber/deletar.html
<form method="post"action="/contas/receber/deletar/{{c.id}}/" >
    {% csrf_token %}
    <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Fechar"><span aria-hidden="true">&times;</span></button>
    <h4 class="modal-title" id="modalLabel"><i class="fa fa-trash" aria-hidden="true"></i> Deletar Conta</h4>
    </div>
    <div class="modal-body">
         <p class="lead">Deseja Realmente Deletar ?</p>
    </div>
    <div class="modal-footer">
        <button class="btn btn-success" type="submit">Sim</button>
        <button type="button" class="btn btn-danger" data-dismiss="modal">Cancelar</button>
    </div>
</form>