advocacia/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('core.urls')),
    url(r'^', include('sites.urls')),
    url(r'^', include('cliente.urls')),
    url(r'^', include('agenda.urls')),
    url(r'^', include('financeiro.urls')),
    url(r'^', include('blog.urls')),
    url(r'^', include('processos.urls')),
    url(r'^', include('controle_usuario.urls')),
    url(r'^', include('diario.urls')),
    url(r'^', include('processo_trabalhista.urls')),
]

blog/urls.py
from django.conf.urls import include, url
from django.views.generic import TemplateView
from blog.views import *
from . import views

urlpatterns = [
    url(r'^blog/$', views.post_list),
    url(r'^blog/all/posts/$', views.list),
    url(r'^blog/post/(?P<pk>[0-9]+)/$', views.post_detail),
    url(r'^blog/post/novo/$', views.post_new, name='post_new'),
    url(r'^blog/nova/tag/$', views.new_tag, name='new_tag'),
    url(r'^blog/post/(?P<pk>[0-9]+)/editar/$', views.post_edit, name='post_edit'),
    url(r'^blog/deletar/post(?P<pk>\d+)/$', views.excluir_post,name='excluir_post'),
    url(r'^tag/(?P<slug>[\w\-]+)/$', TagPostsView.as_view(), name='tag_posts_page'),
]

blog/models.py
from django.db import models
from django.utils import timezone

class Post(models.Model):
    author = models.ForeignKey('auth.User')
    title = models.CharField(verbose_name='Titulo', max_length=200, blank=True)
    text = models.TextField(verbose_name='Texto', null=True, blank=True)
    tags = models.ManyToManyField('Tag')
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)

    class Meta:
        ordering = ('published_date',)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title

class Tag(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, unique=True)

    def __str__(self):
        return self.title
        
    class Meta:
        verbose_name = 'Tag'
        verbose_name_plural = 'Tags'
class Pictures(models.Model):
    pass
    # post = models.ForeignKey(Post)
    # img = models.

blog/forms.py
from django import forms
from .models import Post,Tag
from django.forms import TextInput, Textarea,CharField,CheckboxSelectMultiple
from tinymce.widgets import TinyMCE

class PostForm(forms.ModelForm):
    text = CharField(widget= TinyMCE(attrs={'cols':120, 'rows': 30}))
    class Meta:
        model = Post
        fields = ('title','tags','text')
        widgets = {
            'title': TextInput(attrs={'class': 'form-control', 'placeholder': 'Digite um título para o post'}),
            'text': Textarea(attrs={'class': 'form-control', 'rows': 30,'placeholder': 'Digite seu post'}),
        }
    def __init__(self, *args, **kwargs):
    
        super(PostForm, self).__init__(*args, **kwargs)
        
        self.fields["tags"].widget = CheckboxSelectMultiple()
        self.fields["tags"].queryset = Tag.objects.all()

class TagForm(forms.ModelForm):

    class Meta:
        model = Tag
        exclude = ['']
        widgets = {
            'title':TextInput(attrs={'class': 'form-control','name':'title' }),
            'slug':TextInput(attrs={'class': 'form-control','name':'slug'}), 
        }

blog/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.utils import timezone
from .models import Post,Tag
from .forms import *
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth.decorators import permission_required
from django.contrib.auth.decorators import login_required
from blog.utils import GenericPaginator
from django.views import generic
def post_list(request):
    tags = Tag.objects.all()
    posts = Post.objects.filter(published_date__lte=timezone.now()).order_by('published_date')
    paginator = Paginator(posts, 4)  # mostrar ate 25 posts por page

    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        posts = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        posts = paginator.page(paginator.num_pages)
    return render(request, 'blog.html', {'posts': posts,'tags':tags})

def list(request):
    posts = Post.objects.filter(published_date__lte=timezone.now()).order_by('published_date')
    return render(request,'lista_de_post.html',{'posts': posts})

def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    tags = Tag.objects.all()
    return render(request, 'post_detalhe.html', {'post': post,'tags':tags})


@login_required(login_url='/usuario/login/')
@permission_required('request.user.is_superuser', login_url='/usuario/login/')
def post_new(request):
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.published_date = timezone.now()
            post.save()
            return redirect("/blog/")
    else:
        form = PostForm()
    return render(request, 'post_edit.html', {'form': form})
    
@permission_required('request.user.is_superuser', login_url='/usuario/login/')
def new_tag(request):
    form = TagForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('post_new')
    return render(request,'post_edit.html',{'tag':form})

   
@login_required(login_url='/usuario/login/')
@permission_required('request.user.is_superuser', login_url='/usuario/login/')
def post_edit(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.published_date = timezone.now()
            post.save()
            return redirect('/blog/')
    else:
        form = PostForm(instance=post)
    return render(request, 'post_edit.html', {'form': form})

@login_required(login_url='/usuario/login/')
def excluir_post(request, pk):
    post = Post.objects.get(id=pk)
    post.delete()
    return redirect("/blog/all/posts/")

class TagPostsView(generic.ListView):
    template_name = 'blog_posts_tag.html'
    paginate_by = 4

    def get_queryset(self):
        slug = self.kwargs['slug']
        self.tag = get_object_or_404(Tag, slug=slug)
        results_filter = Post.objects.filter(
            tags=self.tag
        ).order_by('-created_date').order_by('-id')
        return results_filter

    def get_context_data(self, **kwargs):
        context_data = super(TagPostsView, self).get_context_data(**kwargs)
        context_data['tag'] = self.tag
        context_data['page_range'] = GenericPaginator(
            self.get_queryset(),
            self.paginate_by,
            self.request.GET.get('page')
        ).get_page_range()
        return context_data

blog/templates/blog.html
{% extends "base_site.html" %}
{% load static %}
{% block title %}
    Blog
{% endblock title %}
{% block container%}
    
	<div id="breadcrumb">
		<div class="container">	
			<div class="breadcrumb">							
				<li><a href="/">Home</a></li>
				<li>Blog</li>			
			</div>		
		</div>	
	</div>
	
	<section id="blog" class="container">
        <div class="blog">
            <div class="row">
                <div class="col-md-8">
                {% for post in posts  %}
                    <div class="blog-item">
                        <div class="row">
                            <div class="col-xs-12 col-sm-2">
                                <div class="entry-meta">
                                    <span id="publish_date">{{ post.published_date|date:"D,d,M,Y" }}</span>
                                    <span><i class="fa fa-user"></i> <a href="#">{{ post.author }}</a></span>
                                </div>
                            </div>
                                
                            <div class="col-xs-12 col-sm-10 blog-content">
                                <h4>{{ post.title }}</h4>
                                <p style="text-color:#000">{{ post.text|safe|truncatewords:"60"|linebreaks  }}</p>
                                <a class="btn btn-primary readmore"href="/blog/post/{{post.pk}}">Leia Mais <i class="fa fa-angle-right"></i></a>
                            </div>
                        </div>    
                    </div><!--/.blog-item-->
                    {% endfor %}
                    
                    <div class="col-md-12">
                        <nav class="text-center">
                            <ul class="pagination">
                                <li>
                                    {% if posts.has_previous %}
                                    <a href="?page={{ posts.previous_page_number }}" aria-label="Previous">
                                        <span aria-hidden="true">&laquo;</span>
                                    </a>
                                    {% endif %}
                                </li>
                                {% for pg in posts.paginator.page_range %}
                                {% if posts.number == pg %}
                                    <li class="active"><a href="?page={{ pg }}">{{ pg }}</a></li>
                                {% else %}
                                    <li><a href="?page={{ pg }}{% if request.GET.search_box %}
                                    &search_box={{ request.GET.search_box }}{% endif %}">{{ pg }}</a></li>
                                {% endif %}
                                {% endfor %}
                                <li>
                                  {% if posts.has_next %}
                                    <a href="?page={{ posts.next_page_number }}" aria-label="Next">
                                        <span aria-hidden="true">&raquo;</span>
                                    </a>
                                    {% endif %}
                                </li>
                            </ul>
                        </nav>
                    </div>
                </div><!--/.col-md-8-->

                <aside class="col-md-4">
                    <div class="widget search">
                        <form role="form">
                            <input type="text" class="form-control search_box" autocomplete="off" placeholder="Pesquisar ">
                        </form>
                    </div><!--/.search-->
    				
    				
                     <style type="text/css">
                         img{
                            border-radius: 5px;
                            margin-bottom: 45px;
                        }
                     </style>

                    <div class="widget categories">
                        <h3>Categorias</h3>
                        <div class="row">
                            <div class="col-sm-6">
                                <ul class="blog_category">
                                    <li><a href="#">internet <span class="badge">04</span></a></li>
                                    <li><a href="#">Smartphones <span class="badge">10</span></a></li>
                                    <li><a href="#">Informação <span class="badge">06</span></a></li>
                                    <li><a href="#">Tecnologia <span class="badge">25</span></a></li>
                                </ul>
                            </div>
                        </div>                     
                    </div><!--/.categories-->
    				
                    <div class="widget tags">
                        <h3>Tag Cloud</h3>
                        <ul class="tag-cloud">
                          {% for tag in tags %}
                            <li><a class="btn btn-xs btn-primary" href="{% url 'tag_posts_page' slug=tag.slug %}">{{ tag.title }}</a></li>
                             {% empty %}
                            <p>Nâo Há tags!</p>
                          {% endfor %}
                        </ul>
                        
                    </div><!--/.tags-->
    				<!--/.blog_gallery
    				<div class="widget blog_gallery">
                        <h3>Nossa Galeria</h3>
                        <ul class="sidebar-gallery">
                            <li><a href="#"><img src="{% static "images/blog/gallery1.png"%}" alt="" /></a></li>
                            <li><a href="#"><img src="{% static "images/blog/gallery2.png"%}" alt="" /></a></li>
                            <li><a href="#"><img src="{% static "images/blog/gallery3.png"%}" alt="" /></a></li>
                            <li><a href="#"><img src="{% static "images/blog/gallery4.png"%}" alt="" /></a></li>
                            <li><a href="#"><img src="{% static "images/blog/gallery5.png"%}" alt="" /></a></li>
                            <li><a href="#"><img src="{% static "images/blog/gallery6.png"%}" alt="" /></a></li>
                        </ul>
                    </div>-->
    			</aside>  
            </div><!--/.row-->
        </div>
    </section><!--/#blog-->
	
{%endblock%}

blog/templates/blog_posts_tag.html
{% extends "base_site.html" %}
{% load static %}
{% block title %}
    Blog
{% endblock title %}
{% block container%}
    
    <div id="breadcrumb">
        <div class="container"> 
            <div class="breadcrumb">                            
                <li><a href="index.html">Home</a></li>
                <li>Blog</li>           
            </div>      
        </div>  
    </div>
    
    <section id="blog" class="container">
        <div class="blog">
            <div class="row">
                <div class="col-md-8">
                  {% for object in object_list %}
                    <div class="post">
                      <h2><a href="">{{ object.title }}</a></h2>
                      <p class="meta">
                        By: <a href="" style="text-transform:uppercase">{{ object.author }}</a> &#9679;
                        at {{ object.created }} &#9679;
                        Posted under:
                        {% for tag in object.tags.all %}
                          <a href="{% url 'tag_posts_page' slug=tag.slug %}">#{{ tag }}</a>{% if not forloop.last %}, {% endif %}
                        {% empty %}Uncategories
                        {% endfor %}
                      </p>

                      {{ object.text|safe|striptags|truncatewords:"50"|linebreaks }}
                      <span style="margin-bottom: .5em;float:right">
                         <a class="btn btn-primary readmore"href="">Leia Mais <i class="fa fa-angle-right"></i></a>
                      </span>
                      <div style="clear:both;border-bottom: 1px solid #000;margin: 10px 0"></div>
                    </div>
                  {% empty %}
                    <p class="alert alert-warning text-center cst__radus"><span class="glyphicon glyphicon-info-sign"></span> Posts com essa tag não existe!</p>
                  {% endfor %}
                    <ul class="pagination pagination-lg">
                        <li><a href="#"><i class="fa fa-long-arrow-left"></i>Página Anterior</a></li>
                        <li class="active"><a href="#">1</a></li>
                        <li><a href="#">2</a></li>
                        <li><a href="#">3</a></li>
                        <li><a href="#">4</a></li>
                        <li><a href="#">5</a></li>
                        <li><a href="#">Proxima Página<i class="fa fa-long-arrow-right"></i></a></li>
                    </ul><!--/.pagination-->
                    
                </div><!--/.col-md-8-->

                <aside class="col-md-4">
                    <div class="widget search">
                        <form role="form">
                            <input type="text" class="form-control search_box" autocomplete="off" placeholder="Pesquisar ">
                        </form>
                    </div><!--/.search-->
                    
                     <style type="text/css">
                         img{
                            border-radius: 5px;
                            margin-bottom: 45px;
                        }
                     </style>

                    <div class="widget categories">
                        <h3>Categorias</h3>
                        <div class="row">
                            <div class="col-sm-6">
                                <ul class="blog_category">
                                    <li><a href="#">Computers <span class="badge">04</span></a></li>
                                    <li><a href="#">Smartphone <span class="badge">10</span></a></li>
                                    <li><a href="#">Gedgets <span class="badge">06</span></a></li>
                                    <li><a href="#">Technology <span class="badge">25</span></a></li>
                                </ul>
                            </div>
                        </div>                     
                    </div><!--/.categories-->
                    
                     <div class="widget tags">
                        <h3>Tag Cloud</h3>
                        <ul class="tag-cloud">
                          {% for tag in tags %}
                            <li><a class="btn btn-xs btn-primary" href="{% url 'tag_posts_page' slug=tag.slug %}">{{ tag.title }}</a></li>
                             {% empty %}
                            <p>Nâo Há tags!</p>
                          {% endfor %}
                        </ul>
                        
                    </div><!--/.tags-->
                    
                    <div class="widget blog_gallery">
                        <h3>Nossa Galeria</h3>
                        <ul class="sidebar-gallery">
                            <li><a href="#"><img src="{% static "images/blog/gallery1.png"%}" alt="" /></a></li>
                            <li><a href="#"><img src="{% static "images/blog/gallery2.png"%}" alt="" /></a></li>
                            <li><a href="#"><img src="{% static "images/blog/gallery3.png"%}" alt="" /></a></li>
                            <li><a href="#"><img src="{% static "images/blog/gallery4.png"%}" alt="" /></a></li>
                            <li><a href="#"><img src="{% static "images/blog/gallery5.png"%}" alt="" /></a></li>
                            <li><a href="#"><img src="{% static "images/blog/gallery6.png"%}" alt="" /></a></li>
                        </ul>
                    </div><!--/.blog_gallery-->
                </aside>  
            </div><!--/.row-->
        </div>
    </section><!--/#blog-->
    
{%endblock%}

blog/templates/lista_de_post.html
{% extends "base_sistema.html" %}
{% load static %}
{% block title %}
	Postagens
{% endblock title %}
{% block conteudo %}
	<div class="row">
        <div class="col-lg-12">
        	<a href="/blog/post/novo/" class="btn btn-primary pull-right h2">
					<span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Postagens
				</a>
            <h1 class="page-header">
            	<i class="fa fa-share-square"></i> Postagens
            </h1>
        </div>
    </div>
    <div class="table-responsive">
		{% if posts %} 
			<table class="table table-striped table-hover">
				<thead >
					<tr class="table table-bordered">
						<th>Cod</th>
						<th><i class="fa fa-user" aria-hidden="true"></i> Titulo</th>
						<th><i class="fa fa-user" aria-hidden="true"></i> Autor</th>
						<th><i class="fa fa-calendar" aria-hidden="true"></i>  Data De Criação</th>
						<th><i class="fa fa-cog " aria-hidden="true"></i> AÇÕES</th>
					</tr>
				</thead>

				<tbody>
				{% for post in posts %}
					<tr>
						<td> {{ forloop.counter}} </td>
						<td><a href=""> {{post.title}}</a></td>
						<td> {{post.author}}</td>
						<td>{{ post.published_date|date:"D,d,M,Y" }}</td>
						<td>
							<a href="{% url "post_edit" post.id %}" class="btn btn-info">
								<span class="glyphicon glyphicon-edit" aria-hidden="true"></span> 
							</a>
							<button type="button"class="btn btn-danger  js-delete-post"data-url="{% url 'excluir_post' post.id %}"><span class="glyphicon glyphicon-trash"></span> 
							</button>
						</td>
					</tr>
					 <!--deletar-->
                    <div class="modal fade" id="delete-post" >
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <form method="post"action="{% url "excluir_post" post.id %}" >
                                    {% csrf_token %}
                                    <div class="modal-header">
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Fechar"><span aria-hidden="true">&times;</span></button>
                                    <h4 class="modal-title" id="modalLabel"><i class="fa fa-trash" aria-hidden="true"></i> Deletar Postagem</h4>
                                    </div>
                                    <div class="modal-body">
                                         <p class="lead">Deseja Realmente Deletar ?</p>
                                    </div>
                                    <div class="modal-footer">
                                        <button class="btn btn-success" type="submit">Sim</button>
                                        <button type="button" class="btn btn-danger" data-dismiss="modal">Cancelar</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
				{% endfor %}	
				</tbody>
			</table>
		{% else %}
			<h2>Sem Registros.</h2>
		{% endif %}
	
		<div>
			<h3>{{ posts |length }} post{{ posts |length|pluralize }}</h3>
		</div>
		</div>
			
{% endblock conteudo %}
{% block js_blog %}
	<script type="text/javascript">
	 /*delete*/
                jQuery(document).ready(function($){
                      $(".js-delete-post").click(function () {
                        $.ajax({
                          url: '/blog/deletar/post(?P<pk>\d+)/',
                          type: 'get',
                          dataType: 'json',
                          beforeSend: function () {
                            jQuery.noConflict(); 
                            $("#delete-post").modal("show");
                          },
                          success: function (data) {
                            $("#delete-post .modal-content").html(data.html_form);
                          }
                        });
                      });

                    });
	</script>
{% endblock js_blog %}

blog/templates/post_detalhe.html
{% extends "base_site.html" %}
{% load static %}
{% block title %}
    Blog Detalhe
{% endblock title %}
{% block container%}
    
    <div id="breadcrumb">
        <div class="container"> 
            <div class="breadcrumb">                            
                <li><a href="index.html">Home</a></li>
                <li>Blog</li>           
            </div>      
        </div>  
    </div>
    
    <section id="blog" class="container">
        <div class="blog">
            <div class="row">
                 <!-- Blog Post Content Column -->
            <div class="col-lg-8">
                <h1>{{ post.title }}</h1>
                <hr>
                    <div class="pull-left">
                        <a href="#"> by <span class="glyphicon glyphicon-user"></span>  {{ post.author }}</a>
                    </div>
                    {% if post.published_date %}
                    <div class="date pull-right">
                        <span class="glyphicon glyphicon-time"></span>  {{ post.published_date }}            
                    {% endif %}
                    </div><br>
                    <style type="text/css">
                        p img{
                            border-radius: 5px;
                            margin-bottom: 45px;
                            width: 750px;
                            height: 300px;
                        }
                     </style>
                <p>{{ post.text|safe|linebreaksbr }}</p>
                <hr>
                
            </div>
                <aside class="col-md-4 pull">
                    <div class="widget search">
                        <form role="form">
                            <input type="text" class="form-control search_box" autocomplete="off" placeholder="Pesquisar ">
                        </form>
                    </div><!--/.search-->
                    
                    <div class="widget categories">
                        <h3>Categorias</h3>
                        <div class="row">
                            <div class="col-sm-6">
                                <ul class="blog_category">
                                    <li><a href="#">internet <span class="badge">04</span></a></li>
                                    <li><a href="#">Smartphones <span class="badge">10</span></a></li>
                                    <li><a href="#">Informação <span class="badge">06</span></a></li>
                                    <li><a href="#">Tecnologia <span class="badge">25</span></a></li>
                                </ul>
                            </div>
                        </div>                     
                    </div><!--/.categories-->
                    
                    <div class="widget tags">
                        <h3>Tag Cloud</h3>
                        <ul class="tag-cloud">
                          {% for tag in tags %}
                            <li><a class="btn btn-xs btn-primary" href="{% url 'tag_posts_page' slug=tag.slug %}">{{ tag.title }}</a></li>
                             {% empty %}
                            <p>Nâo Há tags!</p>
                          {% endfor %}
                        </ul>
                        
                    </div><!--/.tags-->
                    <!--/.blog_gallery
                    <div class="widget blog_gallery">
                        <h3>Nossa Galeria</h3>
                        <ul class="sidebar-gallery">
                            <li><a href="#"><img src="{% static "images/blog/gallery1.png"%}" alt="" /></a></li>
                            <li><a href="#"><img src="{% static "images/blog/gallery2.png"%}" alt="" /></a></li>
                            <li><a href="#"><img src="{% static "images/blog/gallery3.png"%}" alt="" /></a></li>
                            <li><a href="#"><img src="{% static "images/blog/gallery4.png"%}" alt="" /></a></li>
                            <li><a href="#"><img src="{% static "images/blog/gallery5.png"%}" alt="" /></a></li>
                            <li><a href="#"><img src="{% static "images/blog/gallery6.png"%}" alt="" /></a></li>
                        </ul>
                    </div>-->
                </aside>  
            </div><!--/.row-->
        </div>
    </section><!--/#blog-->
    
{%endblock%}

blog/templates/post_edit.html
{% extends 'base_sistema.html' %}
{% load static %}
{% block title %}
	Add  Post
{% endblock title %}
{% block blog %}
    <!-- arquivos do blog  -->
    <script src="{% static 'js/tinymce/tinymce.min.js' %}"></script>
    <script src="{% static 'js/tinymce/langs/pt_BR.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/tinymce/custon.js' %}" ></script>
    <script type="text/javascript"> tinyMCE.init({mode:"#id_text"}); </script>
{% endblock %}
{% block conteudo %}
		<div class="panel panel-primary">
			<div class="panel-heading">
				<h3 class="panel-title text-center"><i class="fa fa-plus" aria-hidden="true"></i> CADASTRAR POSTAGENS</h3>
			</div>
			<style>
           #id_tags{
            list-style:none;
           }
       </style>
			<div class="panel-body">
				<form action="" class="form-horizontal" method="POST">
					{% csrf_token %}
					{{ form.errors.as_p }}
					<b>{{form.title.label}}</b>
					{{form.title}}
					<b>{{form.tags.label}}</b> <a href="#" class="js-add-tag"title="Adicionar Uma Tag"> <i class="fa fa-plus text-success" aria-hidden="true"></i></a>
					{{form.tags}}
					<b>{{form.text.label}}</b>
					{{form.text}}

					<button type="submit" class="btn btn-primary">
						<span class="glyphicon glyphicon-floppy-disk" aria-hidden="true"></span> Salvar
					</button>
					<a class="btn btn-success" href=""><i class="fa fa-arrow-left" aria-hidden="true"></i>  Voltar</a>
				</form>
			</div>
		</div>
		<!-- Modal pra add as novas categorias de contas -->
	    <div class="modal fade" id="add-tag-modal" >
	        <div class="modal-dialog" role="document">
	            <div class="modal-content">
	                <form method="post" action="{% url "new_tag" %}" >
	                	{% csrf_token %}
	                    <div class="modal-header">
	                    <button type="button" class="close" data-dismiss="modal" aria-label="Fechar"><span aria-hidden="true">&times;</span></button>
	                    <h4 class="modal-title" id="modalLabel"><i class="fa fa-plus" aria-hidden="true"></i> Adicionar Uma Nova Tag</h4>
	                    </div>
	                    <div class="modal-body">
	                        <div class="container">
							   <div class="col-md-4"> 
							        <b>Tag:</b><input type="text"class="form-control" name='title'>
							        <b>Slug:</b><input type="text"class="form-control" name='slug' >
								</div>
							</div>
	                    </div>
	                    <div class="modal-footer">
	                    	<button class="btn btn-success" type="submit">Cadastrar</button>
	                    	<button type="button" class="btn btn-danger" data-dismiss="modal">Cancelar</button>
	                    </div>
	                </form>
	            </div>
	        </div>
	    </div>
{% endblock %}
{% block js_blog %}
	<script type="text/javascript">
            /*modal create*/
            $(function ($) {
                  $(".js-add-tag").click(function () {
                    $.ajax({
                      url: '/blog/nova/tag/',
                      type: 'get',
                      dataType: 'json',
                      beforeSend: function () {
                        jQuery.noConflict(); 
                        $("#add-tag-modal").modal("show");
                      },
                      success: function (data) {
                        $("#add-tag-modal .modal-content").html(data.html_form);
                      }
                    });
                  });

                });
           
    </script>
{% endblock js_blog %}