advocacia/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('core.urls')),
    url(r'^', include('sites.urls')),
    url(r'^', include('cliente.urls')),
    url(r'^', include('agenda.urls')),
    url(r'^', include('financeiro.urls')),
    url(r'^', include('blog.urls')),
    url(r'^', include('processos.urls')),
    url(r'^', include('controle_usuario.urls')),
    url(r'^', include('diario.urls')),
    url(r'^', include('processo_trabalhista.urls')),
]

agenda/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^agenda/$', views.home),
    url(r'^agenda/(?P<pk>\d+)/$', views.detalhes,name="detalhes_evento"),
    url(r'^agenda/registro_evento/$', views.novo_evento,name="novo_evento"),
    url(r'^agenda/delete/(?P<pk>\d+)/$', views.deletar,name="deletar_evento"),
    url(r'^agenda/atualizar/(?P<pk>\d+)/$', views.atualizar_contato),
]

blog/urls.py
from django.conf.urls import include, url
from django.views.generic import TemplateView
from blog.views import *
from . import views

urlpatterns = [
    url(r'^blog/$', views.post_list),
    url(r'^blog/all/posts/$', views.list),
    url(r'^blog/post/(?P<pk>[0-9]+)/$', views.post_detail),
    url(r'^blog/post/novo/$', views.post_new, name='post_new'),
    url(r'^blog/nova/tag/$', views.new_tag, name='new_tag'),
    url(r'^blog/post/(?P<pk>[0-9]+)/editar/$', views.post_edit, name='post_edit'),
    url(r'^blog/deletar/post(?P<pk>\d+)/$', views.excluir_post,name='excluir_post'),
    url(r'^tag/(?P<slug>[\w\-]+)/$', TagPostsView.as_view(), name='tag_posts_page'),
]

agenda/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.utils.translation import ugettext_lazy as _
from .choices import UF
from django.contrib.auth.models import User
from cliente.models import Cliente
from controle_usuario.models import funcionario

class Evento(models.Model):

    id_evento = models.AutoField(_('id'), primary_key=True)
    cliente   = models.ForeignKey(Cliente, null = True, blank = True)
    usuario   = models.ForeignKey(funcionario, null = True, blank = True)
    titulo    = models.CharField(_('Titulo'), max_length=60)
    data      = models.DateField(blank=False, null=False)
    hora      = models.TimeField(_('Hora'), blank=False, null=True)
    endereco  = models.CharField(_('Endereço'), max_length=80, blank=True, null=True)
    uf        = models.CharField( _('UF'), max_length=2, blank=True, null=True, choices=UF)
    telefone  = models.CharField(_('Telefone'), max_length=20, blank=True, null=True)
    email     = models.EmailField(_('E-mail'), max_length=300, blank=True, null=True)
    bairro    = models.CharField(_('Bairro'), max_length=20, blank=True, null=True)
    anotacao  = models.TextField(blank=True, null=True)

    class Meta:
        ordering = ('data',)
        verbose_name = _('Evento')
        verbose_name_plural = _('Eventos')

    def __str__(self):
        return self.titulo

agenda/forms.py
# -*- coding: utf-8 -*-
from django import forms
from django.forms import ModelForm,TextInput,DateInput,Select,EmailInput
from django.utils.translation import ugettext_lazy as _

from .models import Evento

class EventoForm(ModelForm):

    class Meta:
        model = Evento
        exclude = ['id_evento']
        widgets = {
                'titulo': TextInput(attrs={'class': 'form-control'}),
                'data': DateInput(attrs={'class': 'form-control datepicker-here','data-language': 'pt'}),
                'hora':TextInput(attrs={'class':'form-control'}),
                'email':EmailInput(attrs={'class':'form-control'}),
                'rua':TextInput(attrs={'class':'form-control'}),
                'endereco':TextInput(attrs={'class':'form-control'}),
                'telefone':TextInput(attrs={'class':'form-control'}),
                'bairro':TextInput(attrs={'class':'form-control','placeholder':' Ex, Bairro piaui'}),
                'uf':Select(attrs={'class':'form-control'}),
                'usuario':Select(attrs={'class':'form-control'}),
                'cliente':Select(attrs={'class':'form-control'}),
            }

agenda/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render, redirect,get_object_or_404
from .models import Evento
from cliente.models import Cliente
from django.http import JsonResponse
from django.template.loader import render_to_string
from django.contrib.auth.models import User
from .forms import EventoForm
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth.decorators import permission_required
from django.contrib.auth.decorators import login_required
import datetime
from django.core import serializers
from django.http import HttpResponse
import json

@login_required(login_url='/usuario/login/')
@permission_required('global_permissions.agenda', login_url='/usuario/error/')
def home(request):

    if request.GET.get('descricao'):

        data_ini = datetime.datetime.strptime(request.GET.get('data_ini'), '%d/%m/%Y').strftime('%Y-%m-%d')
        data_fin = datetime.datetime.strptime(request.GET.get('data_fin'), '%d/%m/%Y').strftime('%Y-%m-%d')
        if(request.GET.get('pesquisa') == 'funcionario'):

            eventos = Evento.objects.filter(data__range=(data_ini, data_fin)).filter(usuario__user__first_name__istartswith=request.GET.get('descricao'))

        elif(request.GET.get('pesquisa') == 'cliente'):

            eventos = Evento.objects.filter(data__range=(data_ini, data_fin)).filter(cliente__nome__istartswith=request.GET.get('descricao'))

        return HttpResponse(serializers.serialize('json', eventos), content_type='application/json')
    else:
        eventos= Evento.objects.all()

    paginator = Paginator(eventos, 10)  # mostrar ate 25 eventos por page

    page = request.GET.get('page')
    try:
        eventos= paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        eventos= paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        eventos= paginator.page(paginator.num_pages)

    return render(request, 'home_agenda.html', {'eventos': eventos})


@login_required(login_url='/usuario/login/')
@permission_required('global_permissions.agenda', login_url='/usuario/error/')
def detalhes(request, pk):

    evento = Evento.objects.get(id_evento=pk)

    context = dict(
        ev=evento
    )
    return render(request, 'detalhe_eventos.html', context)


@login_required(login_url='/usuario/login/')
@permission_required('global_permissions.agenda', login_url='/usuario/error/')
def deletar(request, pk):
    evento = get_object_or_404(Evento,id_evento=pk)
    data = dict()
    if request.method == 'POST':
        evento.delete()
        data['form_is_valid'] = True
        return redirect('/agenda/')
    else:
        context = {'evento': evento}
        data['html_form'] = render_to_string('modal.html', context, request=request)
    return JsonResponse(data)


@login_required(login_url='/usuario/login/')
@permission_required('global_permissions.agenda', login_url='/usuario/error/')
def novo_evento(request):

    context = dict(

        form_ev=EventoForm()
    )

    if request.POST:
        form = EventoForm(request.POST)

        if not form.is_valid():
            return render(request, 'novo_evento.html', dict(form_ev=form))

        form.save()
        return redirect('/agenda/')
    return render(request, 'novo_evento.html', context)


@login_required(login_url='/usuario/login/')
@permission_required('global_permissions.agenda', login_url='/usuario/error/')
def atualizar_contato(request, pk):
    evento = Evento.objects.get(id_evento=pk)

    context = dict(
        form_ev=EventoForm(instance=evento)
    )

    if request.POST:
        form = EventoForm(request.POST, instance=evento)

        if not form.is_valid():
            return render(
                request, 'atualizar_evento.html', dict(
                    form_ev=form
                )
            )

        form.save()
        return redirect('/agenda/')
    return render(request, 'atualizar_evento.html', context)

agenda/templates/atualizar_evento.html
{% extends "base_sistema.html" %}
{% load static %}
{% block title %}
  Atualizar
{% endblock title %}
{# Adding select2 css #}
{% block css %}
    <link href=" {% static "js/selects/select2.css" %}"rel="stylesheet">
{% endblock %}

{# Adding select2 js #}
{% block js %}
    <script src="{% static "js/selects/select2.min.js" %}"></script>
{% endblock %}
{% block conteudo %}
	<div class="panel panel-primary">
		<div class="panel-heading">
			<h3 class="panel-title text-center"><i class="fa fa-pencil" aria-hidden="true"></i> Atualizar Evento</h3>
		</div>
		<div class="panel-body">
			<form action="" class="form-horizontal" method="POST">
            {% csrf_token %}
            <div class="row">
                <div class="col-md-7"> 
                    <div class="form-group">
                        <label for="titulo" class="col-sm-2 control-label">{{form_ev.titulo.label}}  <i class="fa fa-user" aria-hidden="true"></i></label>
                        <div class="col-sm-8">
                        {{form_ev.titulo.errors}}
                            {{form_ev.titulo}}
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="data" class="col-sm-2 control-label">{{form_ev.data.label}}  <i class="fa fa-calendar" aria-hidden="true"></i></label>
                        <div class="col-sm-8">
                        {{form_ev.data.errors}}
                            {{form_ev.data}}
                        </div>
                    </div>
                    
                    <div class="form-group">
                        <label class="col-sm-2 control-label">{{form_ev.hora.label}}  <i class="fa fa-clock-o" aria-hidden="true"></i></label>
                        <div class="col-sm-8">
                        {{form_ev.hora.errors}}
                            {{form_ev.hora}}
                        </div>
                    </div>
                    
                    <div class="form-group">
                        <label for="endereco" class="col-sm-2 control-label">{{form_ev.endereco.label}} <i class="fa fa-map-marker" aria-hidden="true"></i> </label>
                        <div class="col-sm-8">
                        {{form_ev.endereco.errors}}
                            {{form_ev.endereco}}
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="bairro" class="col-sm-2 control-label">{{form_ev.bairro.label}} <i class="fa fa-globe" aria-hidden="true"></i></label>
                        <div class="col-sm-8">
                        {{form_ev.bairro.errors}}
                            {{form_ev.bairro}}
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="uf" class="col-sm-2 control-label">{{form_ev.uf.label}} <i class="fa fa-check" aria-hidden="true"></i></label>
                        <div class="col-sm-8">
                        {{form_ev.uf.errors}}
                            {{form_ev.uf}}
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="descricao" class="col-sm-2 control-label">{{form_ev.telefone.label}} <i class="fa fa-pencil" aria-hidden="true"></i></label>
                        <div class="col-sm-8">
                        {{form_ev.telefone.errors}}
                            {{form_ev.telefone}}
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="email" class="col-sm-2 control-label">{{form_ev.email.label}} <i class="fa fa-envelope" aria-hidden="true"></i></label>
                        
                        <div class="col-sm-8">
                        {{form_ev.email.errors}}
                            {{form_ev.email}}
                        </div>
                    </div>
            </div>
            <div class="col-md-5">
                 <div class="form-group">
                    <label for="data" class="col-sm-2 control-label">Cliente</label>
                    <div class="col-sm-8">
                        {{form_ev.cliente.errors}}
                        {{form_ev.cliente}}
                    </div>
                </div>
                <div class="form-group">
                    <label for="titulo" class="col-sm-2 control-label">Advogado </label>
                    <div class="col-sm-8">
                    {{form_ev.usuario.errors}}
                        {{form_ev.usuario}}
                    </div>
                </div>
            </div>
            </div>
                <button type="submit" class="btn btn-primary">
                    <span class="glyphicon glyphicon-floppy-disk" aria-hidden="true"></span> Salvar
                </button>
                <a class="btn btn-success" href="/agenda/"><i class="fa fa-arrow-left" aria-hidden="true"></i>  Voltar</a>
        </form>
		</div>
		<script type="text/javascript"> 
        jQuery.noConflict();
        jQuery(function($){
           $('#id_cliente-' + '-cliente').select2();
           $('select').select2();
           $("#id_telefone").mask("(099) 9999-9999");
           $("#id_hora").mask("99:99");
        });
      </script> 
	</div>
{% endblock %}

agenda/templates/detalhe_eventos.html
{% extends "base_sistema.html" %}
{% load staticfiles %}
{% block title %}
   Detalhes
{% endblock title %}
{% block conteudo %}
<div class="col-md-1"></div>
<div class="col-lg-10">
    <div class="panel panel-success">
        <div class="panel-heading">
            <i class="fa fa-legal fa-fw"></i> Detalhes do Evento
        </div>
        <!-- /.panel-heading -->
            <div class="panel-body">
                <div class="list-group">
                    <li href="#" class="list-group-item">
                        <i class="fa fa-user fa-fw"></i> Funcionário
                            <span class="pull-right text-muted small"><b>{{ ev.usuario }}</b>
                        </span>
                    </li>
                    <li href="#" class="list-group-item">
                        <i class="fa fa-users fa-fw"></i> Cliente
                            <span class="pull-right text-muted small"><b>{{ ev.cliente }}</b>
                        </span>
                    </li>
                    <li href="#" class="list-group-item">
                        <i class="fa fa-calendar fa-fw"></i> Titulo/Data/Hora
                            <span class="pull-right text-muted small"><b> {{ ev.titulo }} {{ ev.data }} {{ ev.hora }}</b>
                        </span>
                    </li>
                    <li href="#" class="list-group-item">
                        <i class="fa fa-map-marker fa-fw"></i> Endereço
                            <span class="pull-right text-muted small"><b>{{ev.endereco}}</b>
                         </span>
                    </li>
                    <li href="#" class="list-group-item">
                        <i class="fa fa-phone fa-fw"></i> Telefone
                            <span class="pull-right text-muted small"><b>{{ev.telefone}}</b>
                        </span>
                    </li>
                     <li href="#" class="list-group-item">
                        <i class="fa fa-globe fa-fw"></i> Uf
                            <span class="pull-right text-muted small"><b>{{ev.get_uf_display}}</b>
                            </span>
                    </li>
                    <li href="#" class="list-group-item">
                        <i class="fa fa-pencil-square-o fa-fw"></i>Anotação
                            <span class="pull-right text-muted small"><b>{{ev.anotacao|default_if_none:'sem '}}</b>
                        </span>
                    </li>
                    <li href="#" class="list-group-item">
                        <i class="fa fa-envelope-o fa-fw"></i> E-mail
                        <span class="pull-right text-muted small"><b>{{ev.email|default_if_none:''}}</b>
                        </span>
                    </li>
                       
                    </div>
                    <!-- /.list-group -->
                    <div class="col-md-4">
                        <a href="/agenda/" class="btn btn-success btn-block"> <i class="fa fa-arrow-left fa-fw"></i> Voltar</a>
                    </div>
                    <div class="col-md-4">
                        <a href="#"class="btn btn-danger btn-block delete_agenda-js" id="{{ev.id_evento}}"><i class="fa fa-trash-o fa-fw"></i> Deletar</a>
                    </div>
                     <div class="col-md-4">
                        <a href="/agenda/atualizar/{{ev.id_evento}}/"class="btn btn-warning btn-block"><i class="fa fa-pencil-square-o fa-fw"></i> Editar</a>
                    </div>
            </div>
        <!-- /.panel-body -->
        <!--deletar com modal-->
            <div class="modal fade" id="delete-agenda-modal" >
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <form method="post"action="/agenda/delete/{{ev.id_evento}}/" >
                            {% csrf_token %}
                            <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-label="Fechar"><span aria-hidden="true">&times;</span></button>
                            <h4 class="modal-title" id="modalLabel"><i class="fa fa-trash" aria-hidden="true"></i> Confirmação de Exclusão</h4>
                            </div>
                            <div class="modal-body">
                                 <p class="lead">Deseja Realmente Deletar Esse Evento ?</p>
                            </div>
                            <div class="modal-footer">
                                <button class="btn btn-success" type="submit">Sim</button>
                                <button type="button" class="btn btn-danger" data-dismiss="modal">Cancelar</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
     </div>
</div>
{% endblock %}

agenda/templates/home_agenda.html
{% extends "base_sistema.html" %}
{% load staticfiles %}
{% block title %}
    Lista De Eventos
  {% endblock title %}
{% block cliente %}
    <link href="{% static "css/admin/calendario.min.css" %}" rel="stylesheet" >
{% endblock %}
{% block conteudo %}
    <div class="row">
        <div class="col-lg-12">
            <a href="{% url "novo_evento" %}" class="btn btn-primary pull-right h2"style="margin-left:5px;">Adicionar Compromisso <i class="fa fa-plus" aria-hidden="true"></i></a>
            <h2 class="page-header">
                <i class="fa fa-calendar-o" aria-hidden="true"></i> Agenda De Compromissos</h2>
            </h2>
        </div>
    </div>
    <div class="row"id="minhaDiv" >
            <div class="col-md-2">                      
                <input type="text" name="data_ini" id="data_ini" class="form-control " data-language="pt"placeholder="Data Inicial"  >
            </div>  
            <div class="col-md-2">                      
                <input type="text" name="data_fin"  id="data_fin" class="form-control " data-language="pt"placeholder="Data Final" value="">
            </div>
            <div class="col-md-3">
                <input type="text" name="descricao" id="descricao" class="form-control" placeholder="Digite a Sua Pesquisa">
            </div>
            <div class="col-md-3">
                <select name="pesquisa" id="pesquisa" class="form-control">
                    <option value='cliente'>Cliente</option>
                    <option value='funcionario'>Funcionario</option>
                </select>
            </div>
            <div class="col-md-1">
                <button class="btn btn-success" id="enviar" type="submit"><i class="fa fa-search" aria-hidden="true"></i> Filtrar</button></p>
            </div>

    </div>
    <div class="table-responsive ">
        {% if eventos %} 
           <table class="table table-striped"cellspacing="0" cellpadding="0"id="desaparecer_table">
                <thead>
                    <tr class="table table-bordered">
                        <th>Nº</th>
                        <th>Nome <i class="fa fa-user" aria-hidden="true"></i></th>
                        <th>Data <i class="fa fa-calendar" aria-hidden="true"></i></th>
                        <th>Hora <i class="fa fa-clock-o" aria-hidden="true"></i></th>
                        <th>Telefone <i class="fa fa-phone" aria-hidden="true"></i></th>
                        <th>Endereço <i class="fa fa-map-marker" aria-hidden="true"></i> 
                        </th>
                        <th class="actions">Ações <i class="fa fa-cog" aria-hidden="true"></i></th>
                    </tr>
                </thead>
                <tbody>
                {% for evento in eventos %} 
                    <tr>
                        <td>{{evento.id_evento}}</td>
                        <td><a href="{% url "detalhes_evento" evento.id_evento %}"> {{evento.titulo}}</a></td>
                        <td>{{evento.data|date:"D,d,M,Y"}}</td>
                        <td>{{evento.hora}}</td>
                        <td>{{evento.telefone}}</td>
                        <td>{{evento.endereco}}</td>
                        <td class="actions">
                            <a class="btn btn-success btn-xs" href="{% url "detalhes_evento" evento.id_evento %}">Visualizar</a>
                            <a class="btn btn-warning btn-xs" href="/agenda/atualizar/{{evento.id_evento}}/">Editar</a>
                            <a class='btn btn-danger btn-xs delete_agenda-js' 
                            id="{{evento.id_evento}}" >Excluir</a>
                        </td>
                    </tr>
                    <!--deletar-->
                    <div class="modal fade" id="delete-agenda-modal" >
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                
                            </div>
                        </div>
                    </div>
                        <!--tabela com o filtros ajax-->
                        <div id="filtro">
                        </div>
                {% endfor %}    
                </tbody>
            </table>
        {% else %}
            <h2 class="alert alert-warning">Sem eventos cadastrados.</h2>
        {% endif %}
            <div>
                <h3>{{eventos|length }} Evento{{eventos|length|pluralize }}</h3>
                <h4><b>Total:</b> {{ eventos.paginator.count }} Evento{{ eventos.paginator.count|pluralize }}</h4>
            </div>
        </div>
            
        <div class="col-md-12">
            <nav class="text-center">
                <ul class="pagination">
                    <li>
                        {% if eventos.has_previous %}
                        <a href="?page={{ eventos.previous_page_number }}" aria-label="Previous">
                            <span aria-hidden="true">&laquo;</span>
                        </a>
                        {% endif %}
                    </li>
                    {% for pg in eventos.paginator.page_range %}
                    {% if eventos.number == pg %}
                        <li class="active"><a href="?page={{ pg }}">{{ pg }}</a></li>
                    {% else %}
                        <li><a href="?page={{ pg }}{% if request.GET.search_box %}
                        &search_box={{ request.GET.search_box }}{% endif %}">{{ pg }}</a></li>
                    {% endif %}
                    {% endfor %}
                    <li>
                      {% if eventos.has_next %}
                        <a href="?page={{ eventos.next_page_number }}" aria-label="Next">
                            <span aria-hidden="true">&raquo;</span>
                        </a>
                        {% endif %}
                    </li>
                </ul>
            </nav>
            <script type="text/javascript">
            jQuery(function($){
                /*funcao que some com a div pesquisa*/
                $('.expander').live('click', function () {
                    $('#minhaDiv').slideToggle();
                });
               $("#data_ini").mask("99/99/9999").datepicker({dateFormat: 'dd/mm/yyyy',autoClose:true});
               $("#data_fin").mask("99/99/9999").datepicker({dateFormat: 'dd/mm/yyyy',autoClose:true});
            });
            </script>
            <script type="text/javascript">
                $(document).ready(function(){
                $('#enviar').click(function(){
                    var data_ini = $("#data_ini").val();
                    var data_fin = $("#data_fin").val();
                    var pesquisa = $("#pesquisa").val();
                    var descricao = $("#descricao").val();
                    var resultado = "<table class='table table-striped' cellspacing='0' cellpadding='0'><thead><tr class='table table-bordered'><th>Nº</th><th>nome <i class='fa fa-user' aria-hidden='true'></i></th><th>Data <i class='fa fa-calendar' aria-hidden='true'></i></th><th>Hora <i class='fa fa-clock-o' aria-hidden='true'></i></th><th>Telefone <i class='fa fa-phone' aria-hidden='true'></i></th><th>Endereço <i class='fa fa-map-marker' aria-hidden='true'></i> </th><th class='actions'>Ações <i class='fa fa-cog' aria-hidden='true'></i></th></tr></thead><tbody>";
                    $.ajax({
                            type: "GET",
                            data: {
                              'data_ini': data_ini,
                              'data_fin': data_fin,
                              'pesquisa': pesquisa,
                              'descricao':descricao
                            },
                            url: '/agenda/',
                            dataType: 'json',
                            success: function (eventos) {
                                $("#desaparecer_table").fadeTo("slow",0.3, function(){
                                    $(this).remove();
                                })

                                $.each(eventos, function(chave, valor){
                                    resultado += "<tr><td>";
                                    resultado += valor["pk"] + "</td> ";
                                    resultado += "<td><a href="+ valor["pk"] +">";
                                    resultado += valor["fields"]["titulo"]+"</a></td>";
                                    resultado += "<td>";
                                    resultado += valor["fields"]["data"]+"</td>";
                                    resultado += "<td>";
                                    resultado += valor["fields"]["hora"]+"</td>";
                                    resultado += "<td>";
                                    resultado += valor["fields"]["telefone"]+"</td>";
                                    resultado += "<td>";
                                    resultado += valor["fields"]["endereco"]+"</td>";
                                    resultado+= "<td class='actions'> <a class='btn btn-success btn-xs' href="+ valor["pk"] +">Visualizar</a> <a class='btn btn-warning btn-xs' href='/agenda/atualizar/"+ valor["pk"] +"/'>Editar</a> <a class='btn btn-danger btn-xs delete_agenda-js' id="+ valor["pk"] +">Excluir</a></td></tr>"
                                });
                                resultado += "</tbody></table>";
                                $("#filtro").html(resultado);
                                /*modal delete*/
                                    jQuery(document).ready(function($){
                                      $(".delete_agenda-js").click(function () {
                                        var btn = $(this);
                                        $.ajax({
                                          url: '/agenda/delete/'+btn.attr("id")+'/',
                                          type: 'GET',
                                          dataType: 'json',
                                          beforeSend: function () {
                                            jQuery.noConflict(); 
                                            $("#delete-agenda-modal").modal("show");
                                          },
                                          success: function (data) {
                                            $("#delete-agenda-modal .modal-content").html(data.html_form);
                                          }
                                        });
                                      });

                                    });
                            },
                            error: function() {
                                //inserir uma msg de erro mais elegante
                                alert("Ocorreu um erro ao carregar os dados.");
                            }
                    });

                });
            });
            </script>
        </div>
{% endblock conteudo %}
{% block js_agenda %}
    <script src="{% static "js/datepicker.min.js" %}"></script>
    <script src="{% static "js/datepicker.pt.js" %}"></script>
{% endblock js_agenda %}

agenda/templates/modal.html
<form method="POST" action="/agenda/delete/{{evento.id_evento}}/"  >
    {% csrf_token %}
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Fechar"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="modalLabel"><i class="fa fa-trash" aria-hidden="true"></i> Confirmação de Exclusão</h4>
    </div>
    <div class="modal-body">
        <p class="lead">Deseja Realmente Deletar Esse Evento ?</p>
    </div>
    <div class="modal-footer">
        <button class="btn btn-success" type="submit">Sim</button>
        <button type="button" class="btn btn-danger" data-dismiss="modal">Cancelar</button>
    </div>
</form>